### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by arichnad** [gostaj/MtGoxWidget#10]
Sorry if this is an inappropriate place to put this issue, but I don't see a forum.  My issue/question is:  where is the source code?

I'm not sure what you're uploading here except the compiled files.  Am I missing something?

**Comment by gostaj** [comment]
Hi Arichnad,
You are correct, the source code hasn't been committed yet due to various
bad excuses. I hope I'll get time for it very soon (next few weeks).

Regards,
Gsta
On Apr 24, 2011 4:30 AM, "arichnad" <
reply@reply.github.com>
wrote:

**Comment by arichnad** [comment]
Any update?  A few weeks have passed.  As I'm sure you noticed, mtgox changed their interface.  I'd like to fix the app to use https (ignoring the server key's status).

**Comment by gostaj** [comment]
Thanks for the heads up with the forced https!
I have now fixed it and released a new version on Market. 
I'm very sorry arichnad for not publishing the code yet, I will do that as soon as possible. Hopefully tomorrow evening!

**Comment by gostaj** [comment]
All source code has now been checked in, please get back to me if you have any problems running the code.

**Comment by arichnad** [comment]
Yes, I was able to pull, build, and install from this.  Much thanks!
