### ISSUE TITLE
24 hour high low now working for bitfloor

### ISSUE THREAD

**Issue by defunctzombie** [gostaj/MtGoxWidget#16]
the high and low numbers say N/A when using the bitfloor data source

**Comment by gostaj** [comment]
The Bitfloor API does unfortunately not include high and low as far as I can see.

https://api.bitfloor.com/ticker/1
https://bitfloor.com/docs/api/market-data/rest

**Comment by defunctzombie** [comment]
why not just track it client side? you get the ticks anyway. you shouldnt need it in the api to give a rough estimate.

**Comment by gostaj** [comment]
Since the client only polls once each 30th minute the highs and lows wouldn't be that accurate and users might think it's the actual highs and lows.
The client polled highs and lows can be seen in the graph if the user is interested.
