### ISSUE TITLE
latest source on github?

### ISSUE THREAD

**Issue by defunctzombie** [gostaj/MtGoxWidget#17]
will the sourcecode continue to be published to github? i see that more exchanges are supported but the repo only mentions mtgox and the source seems to indicate this.

**Comment by gostaj** [comment]
The code is up to date, I haven't changed anything in a while.
Source code file names remain from the time when MtGox was the only supported exchange.

The settings for each exchange can be found here;
https://github.com/gostaj/MtGoxWidget/blob/master/src/st/brothas/mtgoxwidget/RateService.java
