### ISSUE TITLE
Long term graph

### ISSUE THREAD

**Issue by gostaj** [gostaj/MtGoxWidget#9]
Make it possible to switch between a week and a day graph.
Requires changes to the DB handler to store some average daily values.

**Comment by weex** [comment]
ExchB has an api for /data/recent that can be used to preload recent history (currently the last 48 hours). Other exchanges implement something similar so it can give the graph a head start at least in terms of trade data.

**Comment by gostaj** [comment]
Weekly and daily graph has been implemented a while ago.
